### ISSUE TITLE
DAX columns

### ISSUE THREAD

**Issue by hunterforpatterns** [Hugoberry/pbixray#12]
hi @Hugoberry ,
First of all, many thanks for this amazing library!
I'm wondering if you have a plans on adding functionality for dax columns obtaining and their expressions?
Thanks in advance for your answer

**Comment by Hugoberry** [comment]
Good idea. Follow how I get on with this in the `dax-columns` branch.

**Comment by Hugoberry** [comment]
Added in the latest release a new property: `dax_columns` that should do it #14

**Comment by hunterforpatterns** [comment]
hi @Hugoberry ,
sorry for late reply.
Thanks a lot!
