### ISSUE TITLE
How do I get relationships of datamodel in PBIX using PBIXRay?

### ISSUE THREAD

**Issue by deepakjangid123** [Hugoberry/pbixray#4]

**Comment by Hugoberry** [comment]
Thanks for the suggestion. I've added a new `relationships` property which you can use in v0.1.17 https://github.com/Hugoberry/pbixray/releases/tag/0.1.17

**Comment by deepakjangid123** [comment]
@Hugoberry When will it be available in PyPi to install?

**Comment by Hugoberry** [comment]
Already in
![image](https://github.com/user-attachments/assets/3cfefe0e-a2d0-4f76-b401-ecb631709a95)
