### ISSUE TITLE
Failing to load Microsoft's Example model

### ISSUE THREAD

**Issue by hbutani** [Hugoberry/pbixray#6]
This is an amazing library. Thank you for this.

I am trying to load [Microsoft's Example Workbook](https://download.microsoft.com/download/4/6/A/46AB5E74-50F6-4761-8EDB-5AE077FD603C/Contoso%20Sales%20for%20Power%20BI%20Designer.zip)

I unzipped and tried to load the `Contoso Sales for Power BI Designer.pbix` file.

I get the following stacktrace:

<img width="939" alt="image" src="https://github.com/user-attachments/assets/ab0ffec5-86f5-45ff-a204-900a7ffcf198">

**Comment by Hugoberry** [comment]
Thanks for providing this type of file.
The simple answer is the submitted PBIX is from the beginning of times, 2015, when PowerBI was still packaging their data model without XPress9 compression. The easiest workaround I can recommend is re-saving the file with PowerBI desktop. The more complex one, is for me to add support for this type of files. 
![image](https://github.com/user-attachments/assets/ace993c7-fbcf-4ede-93df-2bda2d60f362)

**Comment by hbutani** [comment]
Ok thanks.

BTW I tested pbixray on all the examples in the [microsoft samples repo](https://github.com/microsoft/powerbi-desktop-samples). Was able to load all of them.

The code snippet:
```python
from pbixray import PBIXRay
from icecream import ic
import glob


def show_model(model):
    ic(model.tables)
    ic(model.metadata)
    ic(model.power_query)
    ic(model.statistics)
    ic(model.dax_tables)
    ic(model.dax_measures)
    ic(model.size)
    ic(model.schema)
    ic(model.relationships)

root_dir = ... # set to path to git clone of repo
for filename in glob.iglob(root_dir + '/**/*.pbix', recursive=True):
    print(filename)
    model = PBIXRay(filename)
    show_model(model)

```

Again thank you for a very useful utility!

**Comment by Hugoberry** [comment]
Imagine running this library over all the publicly available PBIX files. I've used the duckdb version of this utility  https://github.com/Hugoberry/duckdb-pbix-extension/ to run such a query over the files in github.

**Comment by hbutani** [comment]
Nice!
