### ISSUE TITLE
Live Connection in Report

### ISSUE THREAD

**Issue by SachinSatam** [Hugoberry/pbixray#7]
Hey, this library has been incredibly helpful, thanks! I’m currently trying to extract metadata (measures, tables, etc.) from a Power BI report that uses a live connection to semantic models. However, when I attempt this, it fails and returns the error: 'DataModel not found in the archive.' I would appreciate any guidance on how to resolve this issue without impacting the original report or its connection. Also any other approach i can try.

**Comment by Hugoberry** [comment]
The primary purpose of this library was to surface the data embedded in the DataModel file inside the pbix file. With a live connection, very little information can be inferred from the connected Semantic Model. And I don't intend to build any functionality supporting connecting to PBI services.
